#include<iostream>
#include<stdlib.h>
#include<limits.h>
#include<ctime>
#include <vector>
#include <numeric>
#include <algorithm>
#include <iomanip>
#include <cmath>

#include "EVRP.hpp"
#include "heuristic.hpp"
#include "stats.hpp"

using namespace std;

static clock_t run_start_clock;
static const double MAX_SECONDS_PER_RUN = 20.0;
static const double MAX_EVALS_PER_RUN = 50000000.0;

/*initialiazes a run for your heuristic*/
void start_run(int r){
  srand(r); //random seed
  run_start_clock = clock();
  init_evals();
  init_current_best();
  cout << "Run: " << r << " with random seed " << r << endl;
}

/*gets an observation of the run for your heuristic*/
void end_run(int r){
  get_mean(r-1,get_current_best()); //from stats.h
  cout << "End of run " << r << " with best solution quality " << get_current_best() << " total evaluations: " << get_evals()  << endl;
  cout << " " << endl;
}

/*sets the termination conidition for your heuristic*/
bool termination_condition(void) {
  bool flag; 
  double elapsed_seconds = (double)(clock() - run_start_clock) / CLOCKS_PER_SEC;
  double eval_limit = TERMINATION;
  if (eval_limit > MAX_EVALS_PER_RUN) {
    eval_limit = MAX_EVALS_PER_RUN;
  }

  if(get_evals() >= eval_limit || elapsed_seconds >= MAX_SECONDS_PER_RUN) 
    flag = true;
  else
    flag = false;

  return flag;
}


/****************************************************************/
/*                  Main Function                               */
/****************************************************************/
int main(int argc, char *argv[]) {

  int run;
  /*Step 1*/
  problem_instance = argv[1];       //pass the .evrp filename as an argument
  read_problem(problem_instance);   //Read EVRP from file from EVRP.h

  /*Step 2*/
  open_stats();//open text files to store the best values from the 20 runs stats.h

  // Edit these two booleans to switch among the 4 variants.
  use_sa = true;
  use_repair = true;
  set_ablation_flags(use_sa, use_repair);

  vector<double> run_results;

  for(run = 1; run <= MAX_TRIALS; run++){
      /*Step 3*/   
      start_run(run);
      //Initialize your heuristic here
      initialize_heuristic(run); //heuristic.h

      /*Step 4*/
      while(!termination_condition()){
        //Execute your heuristic
        run_heuristic();  //heuristic.h
      }

      if (best_sol != nullptr) {
        run_results.push_back(best_sol->tour_length);
      }

      print_solution(best_sol->tour,best_sol->steps);
      if (use_repair) {
        check_solution(best_sol->tour,best_sol->steps);
      }
      /*Note that the solution generated by the random heuristic may not 
      be feasisble in terms of energy when check_solution is utilized. 
      The implementation is only for your reference*/
     /*Step 5*/
     end_run(run);  //store the best solution quality for each run
  }
  /*Step 6*/
  close_stats(); //close text files to calculate the mean result from the 20 runs stats.h

  if (!run_results.empty()) {
      double best_val = *min_element(run_results.begin(), run_results.end());
      double worst_val = *max_element(run_results.begin(), run_results.end());
      double sum_val = accumulate(run_results.begin(), run_results.end(), 0.0);
      double mean_val = sum_val / run_results.size();
      double sq_sum = 0.0;
      for (double v : run_results) {
        double diff = v - mean_val;
        sq_sum += diff * diff;
      }
      double std_dev = sqrt(sq_sum / run_results.size());

      cout << "==========================================" << endl;
      cout << "             FINAL RESULTS SUMMARY        " << endl;
      cout << "==========================================" << endl;
      cout << fixed << setprecision(2);
      cout << " Best  Fitness : " << best_val << endl;
      cout << " Mean  Fitness : " << mean_val << endl;
      cout << " Std. Dev      : " << std_dev << endl;
      cout << " Worst Fitness : " << worst_val << endl;
      cout << "==========================================" << endl;
  }

  //free memory
  free_stats();
  free_heuristic();
  free_EVRP();

  return 0;
}